[package]
name = "osmosis-destinations"
version = { workspace = true }
authors = ["Marc <marc@yieldmos.com>"]
description = "Generalized message generators and compounding preferences used by Yieldmos outpost contracts"
edition = { workspace = true }

[features]


[dependencies]
cosmwasm-std = { workspace = true }
cw-storage-plus = { workspace = true }
cosmwasm-schema = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
cosmos-sdk-proto = { workspace = true }
cw20 = { workspace = true }
outpost-utils = { workspace = true }
cw20-stake = { workspace = true }
cw20-vesting = { workspace = true }
bond-router = { workspace = true, optional = true }
cw-grant-spec = { workspace = true }
osmosis-std = { workspace = true }
sail-destinations = { workspace = true }
membrane = { workspace = true }
struct_iterable = { workspace = true }
